### PR TITLE
EE3 Support and Grid+Bloqs Compatibility

### PR DESCRIPTION
**Pull request by JeroenOnstuimig**
Only tested in EE3 but should still work in EE2.

### CODE REVIEW

**Comment by wesbaker** [comment]
I haven't tested this yet, but it looks reasonable. Could I ask you to make two changes to your formatting:

- Follow ExpressionEngine's [Code Indenting](https://docs.expressionengine.com/latest/development/guidelines/general.html#code-indenting) guidelines, specifically opening `{` should be on a new line
- Always use brackets with conditionals, where, etc. With your changes there were a few if statements without brackets.

**Comment by JeroenOnstuimig** [comment]
Sure! Fixed the formatting.

**Comment by wesbaker** [comment]
Looks a lot better, thanks for the edits. Any chance you could verify it works in EE2?

**Comment by JeroenOnstuimig** [comment]
No sorry, don't have the time. Made this because I needed the field for an EE3 project I'm working on.

**Pull request closed without merging**
