### PR TITLE
Updated for EE3+ compatibility

### PR DESCRIPTION
**Pull request by ignetic**
Also added "double pane" selector for multiselects

### CODE REVIEW

**Comment by wesbaker** [comment]
Double Pane? Could you show me what it looks like? A gif or video would be awesome, but screenshots would work too.

**Comment by ignetic** [comment]
Yes sure, this simply adds jQuery MultiSelect to create the two panes:

You can see this working at http://loudev.com/

**Comment by ignetic** [comment]
I’ve just noticed a merge request by JeroenOnstuimig named “EE3 Support and Grid+Bloqs Compatibility”. 

https://github.com/wesbaker/category_select.ee2_addon/pull/21

 

You may want to look at this instead… would’ve saved me a bit of work there too :| (although I think the addition of “Double Panel” works well for single level lists).

 

Thanks

**Comment by wesbaker** [comment]
I had seen that pull request, but the person who submitted it never tested it on EE2 and I didn't have the time myself. I'm guessing with the EE2 variable in the code, you've tested it in EE2?

**Comment by ignetic** [comment]
Yes I have tested this in EE2. In fact the original code for EE2 hasn't really changed much besides the conditions used around it. 

I also tested JeroenOnstuimig's version where the original functionality worked although the newly added Grid support didn't fully work in EE2 and I am unable to test for blocks/bloqs. So it seems that his version doesn't completely work in EE2. 

Ideally it would be good for this to support Grid and Bloqs too in future :)

**Comment by wesbaker** [comment]
That works for me then. Someone else can come in and add support if they need it. Thanks for the pull request.

**Pull request merged**
